DATALOADER:
  BATCH_SIZE: 128
  SHUFFLE: True
  NUM_WORKERS: 8

LR: 0.01
EPOCH: 200

CRITERION:
  TYPE: CrossEntropyLoss

OPTIMIZER:
  TYPE: SGD
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

SCHEDULER:
  TYPE: MultiStepLR
  MILESTONES: [60, 120, 160]
  GAMMA: 0.2

  WARMUP:
    INIT_LR: 0.00001
    WARMUP_STEPS: 10
    STRATEGY: linear
