DATALOADER:
  BATCH_SIZE: 128
  SHUFFLE: True
  NUM_WORKERS: 4

LR: 0.0005
EPOCH: 300

CRITERION:
  TYPE: CrossEntropyLoss

OPTIMIZER:
  TYPE: AdamW
  WEIGHT_DECAY: 0.05

SCHEDULER:
  TYPE: CosineAnnealingLR
  T_MAX: 280
  ETA_MIN: 0.000005

  WARMUP:
    INIT_LR: 0.0000005
    WARMUP_STEPS: 20
    STRATEGY: linear
